version: '3'
services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - ./postgres_data/:/var/lib/postgresql/
    environment:
      - POSTGRES_USER=blackbox
      - POSTGRES_PASSWORD=blackbox
      - POSTGRES_DB=blackbox
      - TZ=Asia/Bishkek
    ports:
      - 5432:5432

  web:
    build: .
    container_name: blackbox
    environment:
      - DJANGO_SETTINGS_MODULE=csv_to_db.settings
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
