# Generated by Django 3.2 on 2022-06-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blackbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('info_count', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('pre_legend', models.PositiveIntegerField(default=0)),
                ('warning', models.PositiveIntegerField(default=0)),
                ('paired_b', models.PositiveIntegerField(default=0)),
                ('legend', models.PositiveIntegerField(default=0)),
                ('lower_b', models.PositiveIntegerField(default=0)),
                ('repeat_legend', models.PositiveIntegerField(default=0)),
                ('upper_a', models.PositiveIntegerField(default=0)),
                ('lower_a', models.PositiveIntegerField(default=0)),
                ('paired_a', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
